modLoader="javafml"
loaderVersion="[32,)" #forge version dep
issueTrackerURL="https://github.com/iChun/LetSleepingDogsLie/issues"

[[mods]]
    modId="dogslie"
    version="${file.jarVersion}" #mandatory
    displayName="Let Sleeping Dogs Lie"
    displayURL="https://ichun.me/"
    authors="iChun"
    description='''
    Lets dogs lie.
    '''

[[dependencies.dogslie]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dogslie]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,1.17)"
    ordering="NONE"
    side="BOTH"
